import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Check,ChevronDown,ChevronLeft,ChevronUp,Clock3,Eye,EyeOff,MoreHorizontal,Pencil,Plus,RotateCcw,ShoppingCart,Sparkles,Trash2,X}from'lucide-react';
import'./styles.css';

type Item={id:string;name:string;done:boolean;category?:string;quantity?:string;unit?:string;note?:string;price?:string;recordedPurchaseAt?:string};
type Category={id:string;name:string;emoji:string};
type PurchaseRecord={id:string;itemName:string;category?:string;quantity?:string;unit?:string;price?:string;purchasedAt:string};
type FamilyList={id:string;name:string;emoji:string;items:Item[];categories?:Category[];purchaseHistory?:PurchaseRecord[]};
type Replenishment={name:string;last:PurchaseRecord;count:number;averageDays?:number;nextDate?:Date;daysUntil?:number};
const marketCategories:Category[]=[{id:'produce',name:'Frutas & Legumes',emoji:'🍎'},{id:'meat',name:'Carne & Peixe',emoji:'🍖'},{id:'bakery',name:'Pão & Confeitaria',emoji:'🍞'},{id:'dairy',name:'Laticínios',emoji:'🥛'},{id:'frozen',name:'Congelados & Conveniente',emoji:'❄️'},{id:'grains',name:'Cereais & Grãos',emoji:'🌾'},{id:'drinks',name:'Bebidas',emoji:'🧃'},{id:'ingredients',name:'Ingredientes & Condimentos',emoji:'🧂'},{id:'snacks',name:'Lanches & Doces',emoji:'🍫'},{id:'cleaning',name:'Limpeza & Higiene',emoji:'🧼'},{id:'pets',name:'Animais',emoji:'🐶'},{id:'medicine',name:'REMÉDIOS',emoji:'💊'},{id:'other',name:'Sem categoria',emoji:'🎰'}];
const seed:FamilyList[]=[{id:'house',name:'TAREFAS DA CASA',emoji:'🌟🏠',items:[{id:'1',name:'Varrer a casa',done:false},{id:'2',name:'Organizar cozinha',done:true}]},{id:'finance',name:'GESTÃO FINANCEIRA',emoji:'💰',items:[{id:'3',name:'Revisar contas da semana',done:false}]},{id:'market',name:'lista de compras MERCADO',emoji:'🛒',categories:marketCategories,items:[{id:'4',name:'Mussarela',done:false,category:'dairy'},{id:'5',name:'Banana',done:false,category:'produce'},{id:'6',name:'Ovos',done:true,category:'dairy'}]}];
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const money=(v?:string)=>{if(!v)return'';const n=Number(v.replace(',','.'));return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):v};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const dayMs=86400000;
const today=()=>new Date().toISOString().slice(0,10);
function App(){
 const[lists,setLists]=useState<FamilyList[]>(()=>{try{const s=localStorage.getItem('family-home-lists');const parsed:FamilyList[]=s?JSON.parse(s):seed;return parsed.map(l=>l.id==='market'||l.name.toUpperCase().includes('MERCADO')?{...l,categories:l.categories?.length?l.categories:marketCategories,purchaseHistory:l.purchaseHistory||[]}:l)}catch{return seed}});
 const[activeId,setActiveId]=useState<string|null>(null),[hideDone,setHideDone]=useState(true),[menu,setMenu]=useState(false),[homeMenu,setHomeMenu]=useState(false),[renameOpen,setRenameOpen]=useState(false),[renameListId,setRenameListId]=useState<string|null>(null),[renameValue,setRenameValue]=useState(''),[newList,setNewList]=useState(false),[listName,setListName]=useState(''),[listEmoji,setListEmoji]=useState('✨');
 const[addOpen,setAddOpen]=useState(false),[newItem,setNewItem]=useState(''),[itemCategory,setItemCategory]=useState(()=>localStorage.getItem('family-home-last-category')||'other'),[categoryPicker,setCategoryPicker]=useState(false),[collapsed,setCollapsed]=useState<Record<string,boolean>>({});
 const[editingItemId,setEditingItemId]=useState<string|null>(null),[itemQuantity,setItemQuantity]=useState(''),[itemUnit,setItemUnit]=useState('un'),[itemNote,setItemNote]=useState(''),[itemPrice,setItemPrice]=useState('');
 const[categoryManager,setCategoryManager]=useState(false),[categoryEditor,setCategoryEditor]=useState(false),[editingCategoryId,setEditingCategoryId]=useState<string|null>(null),[categoryName,setCategoryName]=useState(''),[categoryEmoji,setCategoryEmoji]=useState('🏷️'),[historyOpen,setHistoryOpen]=useState(false),[insightsOpen,setInsightsOpen]=useState(false);
 const[historyEntryOpen,setHistoryEntryOpen]=useState(false),[historyName,setHistoryName]=useState(''),[historyDate,setHistoryDate]=useState(today()),[historyQuantity,setHistoryQuantity]=useState(''),[historyUnit,setHistoryUnit]=useState('un'),[historyPrice,setHistoryPrice]=useState(''),[historyCategory,setHistoryCategory]=useState('other');
 const cloudReady=useRef(false),applyingRemote=useRef(false),saveTimer=useRef<number|undefined>(undefined),ignoreRemoteUntil=useRef(0),swipeGesture=useRef<{id:string;x:number;y:number;startOffset:number;moved:boolean}|null>(null);
 const[swipedItemId,setSwipedItemId]=useState<string|null>(null),[swipeOffset,setSwipeOffset]=useState<{id:string;x:number}|null>(null);
 const normalizeLists=(incoming:FamilyList[])=>incoming.map(l=>l.id==='market'||l.name.toUpperCase().includes('MERCADO')?{...l,categories:l.categories?.length?l.categories:marketCategories,purchaseHistory:l.purchaseHistory||[]}:l);
 useEffect(()=>{
  let cancelled=false;
  const applyRemote=(payload:unknown)=>{if(cancelled||!Array.isArray(payload)||Date.now()<ignoreRemoteUntil.current)return;applyingRemote.current=true;setLists(normalizeLists(payload as FamilyList[]));window.setTimeout(()=>{applyingRemote.current=false},0)};
  const connect=async()=>{const cloud=(window as any).familyHomeCloud;if(!cloud?.currentMembership)return;cloudReady.current=true;const remote=await cloud.loadLists?.();if(Array.isArray(remote)&&remote.length)applyRemote(remote);else await cloud.saveLists?.(lists)};
  const onReady=()=>{void connect()};
  const onData=(e:Event)=>applyRemote((e as CustomEvent).detail?.payload);
  window.addEventListener('family-home-family-ready',onReady);
  window.addEventListener('family-home-cloud-data',onData);
  void connect();
  return()=>{cancelled=true;window.removeEventListener('family-home-family-ready',onReady);window.removeEventListener('family-home-cloud-data',onData)};
 },[]);
 useEffect(()=>{try{localStorage.setItem('family-home-lists',JSON.stringify(lists))}catch{}if(!cloudReady.current||applyingRemote.current)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>{void (window as any).familyHomeCloud?.saveLists?.(lists)},350);return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current)}},[lists]);
 const active=useMemo(()=>lists.find(l=>l.id===activeId),[lists,activeId]);
 const updateActive=(fn:(l:FamilyList)=>FamilyList)=>setLists(ls=>ls.map(l=>l.id===activeId?fn(l):l));
 const resetEditor=()=>{setEditingItemId(null);setNewItem('');setItemQuantity('');setItemUnit('un');setItemNote('');setItemPrice('');setCategoryPicker(false)};
 const openAdd=()=>{resetEditor();setItemCategory(localStorage.getItem('family-home-last-category')||'other');setAddOpen(true)};
 const openEdit=(item:Item)=>{setEditingItemId(item.id);setNewItem(item.name);setItemQuantity(item.quantity||'');setItemUnit(item.unit||'un');setItemNote(item.note||'');setItemPrice(item.price||'');setItemCategory(item.category||'other');setCategoryPicker(false);setAddOpen(true)};
 const closeAdd=()=>{setAddOpen(false);resetEditor()};
 const saveItem=()=>{const name=newItem.trim();if(!name)return;updateActive(l=>editingItemId?{...l,items:l.items.map(i=>i.id===editingItemId?{...i,name,category:itemCategory,quantity:itemQuantity.trim()||undefined,unit:itemQuantity.trim()?itemUnit:undefined,note:itemNote.trim()||undefined,price:itemPrice.trim()||undefined}:i)}:{...l,items:[...l.items,{id:uid(),name,done:false,category:itemCategory,quantity:itemQuantity.trim()||undefined,unit:itemQuantity.trim()?itemUnit:undefined,note:itemNote.trim()||undefined,price:itemPrice.trim()||undefined}]});localStorage.setItem('family-home-last-category',itemCategory);closeAdd()};
 const deleteItemById=(id:string)=>{setLists(ls=>{const next=ls.map(l=>l.id===activeId?{...l,items:l.items.filter(i=>i.id!==id)}:l);ignoreRemoteUntil.current=Date.now()+1800;if(saveTimer.current)window.clearTimeout(saveTimer.current);try{localStorage.setItem('family-home-lists',JSON.stringify(next))}catch{}const cloud=(window as any).familyHomeCloud;if(cloudReady.current&&cloud?.saveLists)void cloud.saveLists(next).finally(()=>window.setTimeout(()=>{ignoreRemoteUntil.current=0},450));return next});setSwipedItemId(null);setSwipeOffset(null)};
 const deleteItem=()=>{if(!editingItemId)return;const id=editingItemId;closeAdd();deleteItemById(id)};
 const swipeStart=(id:string,e:React.TouchEvent)=>{if(e.touches.length!==1)return;const t=e.touches[0];swipeGesture.current={id,x:t.clientX,y:t.clientY,startOffset:swipedItemId===id?-78:0,moved:false};setSwipeOffset({id,x:swipedItemId===id?-78:0})};
 const swipeMove=(id:string,e:React.TouchEvent)=>{const g=swipeGesture.current;if(!g||g.id!==id||e.touches.length!==1)return;const t=e.touches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>7)return;if(Math.abs(dx)>6)g.moved=true;const x=Math.max(-84,Math.min(0,g.startOffset+dx));setSwipeOffset({id,x})};
 const swipeEnd=(id:string)=>{const g=swipeGesture.current;if(!g||g.id!==id)return;const x=swipeOffset?.id===id?swipeOffset.x:g.startOffset;const open=x<-38;setSwipedItemId(open?id:null);setSwipeOffset(open?{id,x:-78}:null);window.setTimeout(()=>{swipeGesture.current=null},0)};
 const swipeClick=(id:string,fn:()=>void)=>{if(swipeGesture.current?.moved)return;if(swipedItemId===id){setSwipedItemId(null);setSwipeOffset(null);return}fn()};
 const finalizePurchase=()=>{updateActive(l=>{const bought=l.items.filter(i=>i.done&&!i.recordedPurchaseAt);if(!bought.length)return l;const now=new Date().toISOString();const ids=new Set(bought.map(i=>i.id));const records=bought.map(i=>({id:uid(),itemName:i.name,category:i.category,quantity:i.quantity,unit:i.unit,price:i.price,purchasedAt:now}));return{...l,purchaseHistory:[...(l.purchaseHistory||[]),...records],items:l.items.map(i=>ids.has(i.id)?{...i,recordedPurchaseAt:now,price:undefined}:i)}});setMenu(false);setHistoryOpen(true)};
 const openHistoryEntry=()=>{setHistoryName('');setHistoryDate(today());setHistoryQuantity('');setHistoryUnit('un');setHistoryPrice('');setHistoryCategory('other');setHistoryEntryOpen(true)};
 const saveHistoryEntry=()=>{const name=historyName.trim();if(!name||!historyDate)return;const purchasedAt=new Date(`${historyDate}T12:00:00`).toISOString();updateActive(l=>({...l,purchaseHistory:[...(l.purchaseHistory||[]),{id:uid(),itemName:name,category:historyCategory,quantity:historyQuantity.trim()||undefined,unit:historyQuantity.trim()?historyUnit:undefined,price:historyPrice.trim()||undefined,purchasedAt}]}));setHistoryEntryOpen(false)};
 const chooseCategory=(id:string)=>{setItemCategory(id);localStorage.setItem('family-home-last-category',id);setCategoryPicker(false)};
 const createList=()=>{const name=listName.trim();if(!name)return;setLists(c=>[...c,{id:uid(),name:name.toUpperCase(),emoji:listEmoji.trim()||'✨',items:[]}]);setListName('');setListEmoji('✨');setNewList(false)};
 const openRenameList=(list:FamilyList)=>{setRenameListId(list.id);setRenameValue(list.name);setRenameOpen(true);setHomeMenu(false)};
 const saveRenameList=()=>{const name=renameValue.trim();if(!name||!renameListId)return;setLists(ls=>ls.map(l=>l.id===renameListId?{...l,name}:l));setRenameOpen(false);setRenameListId(null);setRenameValue('')};
 const startNewCategory=()=>{setEditingCategoryId(null);setCategoryName('');setCategoryEmoji('🏷️');setCategoryEditor(true)};
 const startEditCategory=(cat:Category)=>{setEditingCategoryId(cat.id);setCategoryName(cat.name);setCategoryEmoji(cat.emoji);setCategoryEditor(true)};
 const saveCategory=()=>{const name=categoryName.trim();if(!name)return;const emoji=categoryEmoji.trim()||'🏷️';updateActive(l=>{const cats=l.categories?.length?[...l.categories]:[...marketCategories];return editingCategoryId?{...l,categories:cats.map(c=>c.id===editingCategoryId?{...c,name,emoji}:c)}:{...l,categories:[...cats,{id:uid(),name,emoji}]}});setCategoryEditor(false);setEditingCategoryId(null);setCategoryName('');setCategoryEmoji('🏷️')};
 const deleteCategory=(id:string)=>{if(id==='other')return;updateActive(l=>({...l,categories:(l.categories||marketCategories).filter(c=>c.id!==id),items:l.items.map(i=>i.category===id?{...i,category:'other'}:i)}));if(itemCategory===id){setItemCategory('other');localStorage.setItem('family-home-last-category','other')}};
 if(active){
  const isMarket=active.id==='market'||active.name.toUpperCase().includes('MERCADO'),cats=isMarket?(active.categories?.length?active.categories:marketCategories):[],visible=hideDone?active.items.filter(i=>!i.done):active.items,selected=cats.find(c=>c.id===itemCategory)??cats[cats.length-1]??marketCategories[marketCategories.length-1];
  const history=[...(active.purchaseHistory||[])].sort((a,b)=>b.purchasedAt.localeCompare(a.purchasedAt));
  const lastFor=(name:string)=>history.find(h=>normalize(h.itemName)===normalize(name));
  const grouped=new Map<string,PurchaseRecord[]>();history.forEach(h=>{const key=normalize(h.itemName);grouped.set(key,[...(grouped.get(key)||[]),h])});
  const replenishment:Replenishment[]=Array.from(grouped.values()).map(records=>{const ordered=[...records].sort((a,b)=>new Date(a.purchasedAt).getTime()-new Date(b.purchasedAt).getTime());const unique=ordered.filter((r,i)=>i===0||new Date(r.purchasedAt).toDateString()!==new Date(ordered[i-1].purchasedAt).toDateString());const last=ordered[ordered.length-1];if(unique.length<2)return{name:last.itemName,last,count:unique.length};const gaps=unique.slice(1).map((r,i)=>(new Date(r.purchasedAt).getTime()-new Date(unique[i].purchasedAt).getTime())/dayMs).filter(d=>d>0);if(!gaps.length)return{name:last.itemName,last,count:unique.length};const averageDays=Math.max(1,Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length));const nextDate=new Date(new Date(last.purchasedAt).getTime()+averageDays*dayMs);const daysUntil=Math.ceil((nextDate.getTime()-Date.now())/dayMs);return{name:last.itemName,last,count:unique.length,averageDays,nextDate,daysUntil}}).sort((a,b)=>(a.daysUntil??9999)-(b.daysUntil??9999));
  const addFromHistory=(r:Replenishment)=>{updateActive(l=>{const existing=l.items.find(i=>normalize(i.name)===normalize(r.name));if(existing)return{...l,items:l.items.map(i=>i.id===existing.id?{...i,done:false,recordedPurchaseAt:undefined,price:undefined,category:i.category||r.last.category,quantity:i.quantity||r.last.quantity,unit:i.unit||r.last.unit}:i)};return{...l,items:[...l.items,{id:uid(),name:r.name,done:false,category:r.last.category||'other',quantity:r.last.quantity,unit:r.last.unit}]}})};
  const toggleItem=(id:string)=>updateActive(l=>({...l,items:l.items.map(i=>i.id===id?{...i,done:!i.done,...(i.done?{recordedPurchaseAt:undefined}:{})}:i)}));
  return <main className="app nativeApp" onClick={()=>menu&&setMenu(false)}>
   <header className="listHeader"><button className="icon" onClick={e=>{e.stopPropagation();setActiveId(null);setMenu(false)}}><ChevronLeft/></button><h1>{active.name} <span>{active.emoji}</span></h1><button className="icon" onClick={e=>{e.stopPropagation();setMenu(v=>!v)}}><MoreHorizontal/></button></header>
   {menu&&<div className="menu" onClick={e=>e.stopPropagation()}><button onClick={()=>{setHideDone(v=>!v);setMenu(false)}}>{hideDone?<Eye/>:<EyeOff/>}{hideDone?'Mostrar concluídos':'Ocultar concluídos'}</button>{isMarket&&<><button onClick={()=>{setInsightsOpen(true);setMenu(false)}}><Sparkles/>Reposição inteligente</button><button onClick={()=>{setHistoryOpen(true);setMenu(false)}}><Clock3/>Histórico de compras</button><button onClick={finalizePurchase}><ShoppingCart/>Finalizar compra</button><button onClick={()=>{setCategoryManager(true);setMenu(false)}}><Pencil/>Gerenciar categorias</button></>}<button onClick={()=>{updateActive(l=>({...l,items:l.items.map(i=>({...i,done:false,recordedPurchaseAt:undefined}))}));setMenu(false)}}><RotateCcw/>Desmarcar todos</button><button onClick={()=>{updateActive(l=>({...l,items:l.items.map(i=>({...i,done:true}))}));setMenu(false)}}><Check/>Concluir todos</button><button className="danger" onClick={()=>{updateActive(l=>({...l,items:l.items.filter(i=>!i.done)}));setMenu(false)}}><Trash2/>Excluir concluídos</button></div>}
   {isMarket&&<button className="quickAdd" onClick={openAdd}><Plus/><span>Adicionar um item</span></button>}
   {isMarket?<section className="categoryGroups">{cats.map(cat=>{const items=visible.filter(i=>(i.category||'other')===cat.id);return <div className={`categoryGroup ${items.length?'':'emptyCategory'}`} key={cat.id}><button className="categoryHeader" onClick={()=>setCollapsed(c=>({...c,[cat.id]:!c[cat.id]}))}><span><strong>{cat.name}</strong><b>{cat.emoji}</b>{items.length>0&&<small>{items.length}</small>}</span>{collapsed[cat.id]?<ChevronDown/>:<ChevronUp/>}</button>{!collapsed[cat.id]&&items.map(item=>{const last=lastFor(item.name),offset=swipeOffset?.id===item.id?swipeOffset.x:(swipedItemId===item.id?-78:0);return <div className="swipeRow" key={item.id}><button className="swipeDelete" onClick={()=>deleteItemById(item.id)} aria-label={`Excluir ${item.name}`}><Trash2 size={22}/><span>Excluir</span></button><div className={`item swipeItem ${item.done?'done':''}`} style={{transform:`translateX(${offset}px)`}} onTouchStart={e=>swipeStart(item.id,e)} onTouchMove={e=>swipeMove(item.id,e)} onTouchEnd={()=>swipeEnd(item.id)} onTouchCancel={()=>swipeEnd(item.id)}><button className="itemCheck" onClick={()=>swipeClick(item.id,()=>toggleItem(item.id))}><span className="check">{item.done&&<Check size={17}/>}</span></button><button className="itemContent" onClick={()=>swipeClick(item.id,()=>openEdit(item))}><span className="itemName">{item.name}</span>{(item.quantity||item.price||item.note||last?.price)&&<small>{item.quantity?`${item.quantity} ${item.unit||''}`:''}{item.price?`${item.quantity?' · ':''}${money(item.price)}`:last?.price?`${item.quantity?' · ':''}último ${money(last.price)}`:''}{item.note?` · ${item.note}`:''}</small>}</button></div></div>})}</div>})}</section>:<section className="items">{visible.map(item=>{const offset=swipeOffset?.id===item.id?swipeOffset.x:(swipedItemId===item.id?-78:0);return <div className="swipeRow" key={item.id}><button className="swipeDelete" onClick={()=>deleteItemById(item.id)} aria-label={`Excluir ${item.name}`}><Trash2 size={22}/><span>Excluir</span></button><div className={`item swipeItem ${item.done?'done':''}`} style={{transform:`translateX(${offset}px)`}} onTouchStart={e=>swipeStart(item.id,e)} onTouchMove={e=>swipeMove(item.id,e)} onTouchEnd={()=>swipeEnd(item.id)} onTouchCancel={()=>swipeEnd(item.id)}><button className="itemCheck" onClick={()=>swipeClick(item.id,()=>toggleItem(item.id))}><span className="check">{item.done&&<Check size={17}/>}</span></button><button className="itemContent" onClick={()=>swipeClick(item.id,()=>openEdit(item))}><span className="itemName">{item.name}</span>{item.note&&<small>{item.note}</small>}</button></div></div>})}</section>}
   <button className="fab" onClick={openAdd}><Plus/></button>
   {insightsOpen&&<div className="nativeOverlay"><section className="nativeSheet insightsSheet"><div className="nativeSheetHead"><button onClick={()=>setInsightsOpen(false)}><X/></button><h2>Reposição</h2><span/></div><div className="insightsIntro"><Sparkles/><div><strong>O Family Home aprende com suas compras</strong><small>Depois de pelo menos 2 compras do mesmo item, calculamos o intervalo médio e estimamos quando ele pode acabar.</small></div></div><div className="insightsList">{replenishment.length===0?<div className="historyEmpty">Finalize uma compra para começar a criar seu histórico.</div>:replenishment.map(r=>{const inList=active.items.some(i=>normalize(i.name)===normalize(r.name)&&!i.done);const status=r.averageDays===undefined?'aprendendo':(r.daysUntil??0)<=0?'hora de repor':(r.daysUntil??0)<=3?'repor em breve':`em ${r.daysUntil} dias`;return <div className="insightRow" key={normalize(r.name)}><div className="insightMain"><strong>{r.name}</strong><small>{r.averageDays?`Costuma durar ~${r.averageDays} dias · última compra ${new Date(r.last.purchasedAt).toLocaleDateString('pt-BR')}`:`${r.count}/2 compras para aprender o intervalo`}</small>{r.last.price&&<small>Último preço: {money(r.last.price)}</small>}</div><div className="insightAction"><span className={`insightStatus ${r.averageDays&&((r.daysUntil??0)<=3)?'due':''}`}>{status}</span><button disabled={inList} onClick={()=>addFromHistory(r)}>{inList?'na lista':'+ adicionar'}</button></div></div>})}</div></section></div>}
   {historyOpen&&<div className="nativeOverlay"><section className="nativeSheet historySheet"><div className="nativeSheetHead"><button onClick={()=>setHistoryOpen(false)}><X/></button><h2>Histórico</h2><button className="confirm" onClick={openHistoryEntry}><Plus/></button></div><div className="historyList">{history.length===0?<div className="historyEmpty">Nenhuma compra registrada ainda.</div>:history.map(h=><div className="historyRow" key={h.id}><div><strong>{h.itemName}</strong><small>{new Date(h.purchasedAt).toLocaleDateString('pt-BR')}{h.quantity?` · ${h.quantity} ${h.unit||''}`:''}</small></div><b>{h.price?money(h.price):'sem preço'}</b></div>)}</div>{historyEntryOpen&&<div className="pickerScrim" onClick={()=>setHistoryEntryOpen(false)}><section className="categoryEditor historyEntryForm" onClick={e=>e.stopPropagation()}><div className="pickerHandle"/><div className="pickerTitle"><h2>Registrar compra anterior</h2></div><label>Produto<input value={historyName} onChange={e=>setHistoryName(e.target.value)} placeholder="Ex.: Leite"/></label><label>Data<input type="date" value={historyDate} max={today()} onChange={e=>setHistoryDate(e.target.value)}/></label><div className="historyEntryGrid"><label>Quantidade<input inputMode="decimal" value={historyQuantity} onChange={e=>setHistoryQuantity(e.target.value)} placeholder="1"/></label><label>Unidade<select value={historyUnit} onChange={e=>setHistoryUnit(e.target.value)}><option>un</option><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pct</option></select></label></div><label>Preço pago<input inputMode="decimal" value={historyPrice} onChange={e=>setHistoryPrice(e.target.value)} placeholder="0,00"/></label><label>Categoria<select value={historyCategory} onChange={e=>setHistoryCategory(e.target.value)}>{cats.map(cat=><option key={cat.id} value={cat.id}>{cat.emoji} {cat.name}</option>)}</select></label><button className="primaryAction" onClick={saveHistoryEntry}>Registrar compra</button></section></div>}</section></div>}
   {categoryManager&&<div className="nativeOverlay"><section className="nativeSheet manageSheet"><div className="nativeSheetHead"><button onClick={()=>setCategoryManager(false)}><X/></button><h2>Categorias</h2><button className="confirm" onClick={startNewCategory}><Plus/></button></div><div className="manageList">{cats.map(cat=><div className="manageCategoryRow" key={cat.id}><button className="manageCategoryMain" onClick={()=>startEditCategory(cat)}><span>{cat.emoji}</span><strong>{cat.name}</strong></button>{cat.id!=='other'&&<button className="miniDanger" onClick={()=>deleteCategory(cat.id)}><Trash2 size={20}/></button>}</div>)}</div>{categoryEditor&&<div className="pickerScrim" onClick={()=>setCategoryEditor(false)}><section className="categoryEditor" onClick={e=>e.stopPropagation()}><div className="pickerHandle"/><div className="pickerTitle"><h2>{editingCategoryId?'Editar categoria':'Nova categoria'}</h2></div><label>Emoji<input className="categoryEmojiInput" value={categoryEmoji} onChange={e=>setCategoryEmoji(e.target.value)}/></label><label>Nome<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="Ex.: Padaria"/></label><button className="primaryAction" onClick={saveCategory}>{editingCategoryId?'Salvar alterações':'Criar categoria'}</button></section></div>}</section></div>}
   {addOpen&&<div className="nativeOverlay"><section className="nativeSheet"><div className="nativeSheetHead"><button onClick={closeAdd}><X/></button><h2>{editingItemId?'Editar':'Adicionar'}</h2><button className="confirm" onClick={saveItem}><Check/></button></div><div className="nativeCard"><label className="nativeRow nameRow"><span className="emptyCircle"/><input value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder="Nome"/></label>{isMarket&&<><button className="nativeRow" onClick={()=>setCategoryPicker(true)}><span className="rowEmoji">{selected.emoji}</span><span>{selected.name}</span></button><div className="nativeRow quantityRow"><span className="lineIcon">#</span><input inputMode="decimal" value={itemQuantity} onChange={e=>setItemQuantity(e.target.value)} placeholder="Quantidade"/><select value={itemUnit} onChange={e=>setItemUnit(e.target.value)}><option>un</option><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pct</option></select></div><label className="nativeRow priceRow"><span className="lineIcon">R$</span><input inputMode="decimal" value={itemPrice} onChange={e=>setItemPrice(e.target.value)} placeholder="Preço pago"/></label></>}<button className="nativeRow"><span className="lineIcon">♙</span><span>Atribuir a</span></button><button className="nativeRow mutedRow"><span className="lineIcon">▣</span><span>Definir data e lembrete</span></button><button className="nativeRow mutedRow"><span className="lineIcon">↻</span><span>Repetir</span></button><div className="nativeRow"><span className="lineIcon">🛒</span><span>{active.name}</span></div><label className="nativeRow noteRow"><span className="lineIcon">▤</span><input value={itemNote} onChange={e=>setItemNote(e.target.value)} placeholder="Adicionar nota"/></label>{editingItemId&&<button className="nativeRow deleteItemRow" onClick={deleteItem}><Trash2 size={21}/><span>Excluir item</span></button>}</div>{categoryPicker&&<div className="pickerScrim" onClick={()=>setCategoryPicker(false)}><section className="categoryPicker" onClick={e=>e.stopPropagation()}><div className="pickerHandle"/><div className="pickerTitle"><h2>Categorias</h2><button onClick={()=>{setCategoryPicker(false);setAddOpen(false);setCategoryManager(true);startNewCategory()}}><Plus/></button></div><div className="categoryOptions">{cats.map(cat=><button className="categoryOption" key={cat.id} onClick={()=>chooseCategory(cat.id)}><span className="categoryEmoji">{cat.emoji}</span><span>{cat.name}</span><span className={`radio ${itemCategory===cat.id?'selected':''}`}>{itemCategory===cat.id&&<i/>}</span></button>)}</div></section></div>}</section></div>}
  </main>
 }
 return <main className="app" onClick={()=>homeMenu&&setHomeMenu(false)}><header className="homeHeader"><div/><h1>Lists</h1><button className="icon" onClick={e=>{e.stopPropagation();setHomeMenu(v=>!v)}}><MoreHorizontal/></button></header>{homeMenu&&<div className="menu homeListMenu" onClick={e=>e.stopPropagation()}><button onClick={()=>{setHomeMenu(false);setRenameOpen(true);setRenameListId(null);setRenameValue('')}}><Pencil/>Editar nomes das listas</button></div>}<section className="lists">{lists.map(list=>{const p=list.items.filter(i=>!i.done).length;return <div className="listRowWrap" key={list.id}><button className="listRow" onClick={()=>setActiveId(list.id)}><span className="emoji">{list.emoji}</span><span className="listText"><strong>{list.name}</strong><small>♧ Shared with family</small></span><span className={`count ${p===0?'complete':''}`}>{p===0?<Check/>:p}</span></button>{renameOpen&&!renameListId&&<button className="renameQuick" aria-label={`Editar nome de ${list.name}`} onClick={()=>openRenameList(list)}><Pencil size={18}/></button>}</div>})}</section><button className="fab" onClick={()=>setNewList(true)}><Plus/></button>{renameOpen&&renameListId&&<div className="overlay" onClick={()=>setRenameOpen(false)}><div className="sheet renameSheet" onClick={e=>e.stopPropagation()}><div className="sheetTitle"><button className="icon" onClick={()=>setRenameOpen(false)}><X/></button><h2>Editar nome</h2><button className="save" onClick={saveRenameList}>Salvar</button></div><label>Nome<input autoFocus value={renameValue} onChange={e=>setRenameValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')saveRenameList()}}/></label></div></div>}{renameOpen&&!renameListId&&<div className="renameHint">Toque no lápis da lista que deseja renomear.</div>}{newList&&<div className="overlay" onClick={()=>setNewList(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheetTitle"><button className="icon" onClick={()=>setNewList(false)}><X/></button><h2>New list</h2><button className="save" onClick={createList}>Create</button></div><label>Emoji<input className="emojiInput" value={listEmoji} onChange={e=>setListEmoji(e.target.value)}/></label><label>Name<input autoFocus value={listName} onChange={e=>setListName(e.target.value)} placeholder="Ex.: VIAGEM"/></label></div></div>}</main>
}
createRoot(document.getElementById('root')!).render(<App/>);